### ISSUE TITLE
Починить инспекции

### ISSUE THREAD

**Issue by oxeg** [java-park-mail-ru/2016-02-crash-effort#9]
Горят в нескольких местах

**Comment by smirnov-vs** [comment]
Подскажите, пожалуйста, насчет инспекций. У меня не горят, и парочку подавлены. Может я что-то не так настроил?

**Comment by oxeg** [comment]
Возможно, у вас не настроен профиль инспекций. Нужно выкачать и подцепить его отсюда: https://github.com/esin88/tp_java/blob/master/tp_java.xml

**Comment by oxeg** [comment]
Как настраивать инспекции написано в [туториале](https://docs.google.com/document/d/1_iTGYBqoJKcW1b7bRwobcc2lrbg3X2NRnDb5mbcbD6g/edit?usp=sharing) по настройке IDEA

**Comment by oxeg** [comment]
Инспекции все еще горят

**Comment by smirnov-vs** [comment]
У меня нет инспекций. Заново подцепил этот файл, но ничего не появилось. Где они горят?

**Comment by oxeg** [comment]
Инспекции все еще горят. У меня это выглядит так: https://s.mail.ru/Jkvg/YtfRv96un

**Comment by smirnov-vs** [comment]
спасибо, получилось починить)
